apiVersion: v1
kind: Service
metadata:
  name: mydb
  ## [수정필요] 개인 네임스페이스 지정
  namespace: <KnoxID>
  labels:
    app: mydb
    knoxid: <KnoxID>
spec:
  ## [수정필요]  Master Pod에 직접 접근하기 위해 Headless Service를 배포