apiVersion: v1
kind: ConfigMap
metadata: 
  name: mydb-service-cm
  ## [수정필요] 개인 네임스페이스 지정
  namespace: <KnoxID>
  labels:
    app: mydb
    knoxid: <KnoxID>
data:
  ## [수정필요] MySQL DB의 1) Headless DNS / 2)읽기전용 Service의 K8S DNS명을 작성
