apiVersion: v1
kind: Secret
metadata:
  name: mydb-secret
  ## [수정필요] 개인 네임스페이스 지정
  namespace: <KnoxID>
  labels:
    app: mydb
    knoxid: <KnoxID>
type: Opaque
data:
  ## [수정필요] MySQL ID(root)와 Password를 작성