## Docker Hub에서 openjdk:17.0.1-jdk 이미지를 다운 및 ECR에 Push 후 베이스 이미지로 지정합니다.
## ex) FROM 495988863529.dkr.ecr.ap-northeast-2.amazonaws.com/openjdk:17.0.1-jdk

## 제공된 app.jar를 내부에 COPY 합니다. 이때 app.jar는 docker build를 실행하는 디렉토리의 하위 디렉토리에 위치해야합니다. 

## 컨테이서 구동 시 app.jar 실행합니다.
