## Docker Hub에서 mysql:5.7 이미지를 다운 및 본인의 ECR에 Push 후 베이스 이미지로 지정합니다.
## ex) FROM 495988863529.dkr.ecr.ap-northeast-2.amazonaws.com/mysql:5.7

## 제공된 DDL(/mysql.init-files/db.sql)을 이미지에 포함합니다.
## docker의 mysql db 구조에서 약속된 형태로 특정 경로에 넣은 sql이나 sh은 시작하자마자 구동됩니다.

## DB 포트는 3306 기본 포트를 사용합니다.

## 컨테이너 구동 시 mysqld 데몬이 실행되도록 합니다.
