apiVersion: v1
kind: Service
metadata:
  name: kukie-portal
  ## [수정필요] 개인 네임스페이스 지정
  namespace: <KnoxID>
  labels:
    app: kukie-portal
    knoxid: <KnoxID>
spec:
  ## [수정필요] Loadbalancer 타입의 포탈 서비스 배포
  ## 관리형 쿠버네티스 서비스인 EKS를 사용함으로서 자동으로 Classic Load Balancer가 할당되고 접속까지 됨을 확인
